default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  port: 3306

development:
  <<: *default
  host: 127.0.0.1
  database: <%= ENV['DB_DEV_NAME'] %>
  username: <%= ENV['DB_DEV_USERNAME'] %>
  password: <%= ENV['DB_DEV_PASSWORD'] %>

test:
  <<: *default
  host: 127.0.0.1
  database: <%= ENV['DB_TEST_NAME'] %>
  username: <%= ENV['DB_TEST_USERNAME'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>

staging:
  <<: *default
  database: <%= ENV['DB_STAGING_NAME'] %>
  username: <%= ENV['DB_STAGING_USERNAME'] %>
  password: <%= ENV['DB_STAGING_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['DB_PRODUCTION_IP'] %>
  database: <%= ENV['DB_PRODUCTION_NAME'] %>
  username: <%= ENV['DB_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DB_PRODUCTION_PASSWORD'] %>

